update MbedTLS dependency link and add Debian / Ubuntu apt pkg-config
shadowsocks/shadowsocks-libev pull request #2940
Opened 2022-10-18 16:44 UTC by rickyrick2002

I tried to build from source on Ubuntu 22.04 LTS today and found `https://tls.mbed.org/download/` link is broken. Also I ran into errors when executing `./autogen.sh`, `error: possibly undefined macro: AC_MSG_ERROR`. `apt install pkg-config` fixes the error and built successfully.

2022-10-24 05:29 UTC, madeye requested changes

2022-10-24 05:29 UTC, madeye commented on README.md
> +wget https://github.com/Mbed-TLS/mbedtls/archive/refs/tags/mbedtls-2.6.0.tar.gz
`2.6.0` should be replaced by `$MBEDTLS_VER`

2022-10-25 03:59 UTC, rickyrick2002 commented on README.md
> +wget https://github.com/Mbed-TLS/mbedtls/archive/refs/tags/mbedtls-2.6.0.tar.gz
Done :)

2022-10-25 03:59 UTC, madeye approved these changes

2022-10-25 03:59 UTC, merged